//nortedeste
        // Conexões a partir de Teresina
        grafoCapitais.adicionarAresta("Teresina", "Sao Luis", 450);
        grafoCapitais.adicionarAresta("Teresina", "Belo Horizonte", 1800);
        grafoCapitais.adicionarAresta("Teresina", "Vitoria", 2000);
        grafoCapitais.adicionarAresta("Teresina", "Rio de Janeiro", 2100);
        grafoCapitais.adicionarAresta("Teresina", "Sao Paulo", 2300);
        grafoCapitais.adicionarAresta("Teresina", "Curitiba", 2600);
        grafoCapitais.adicionarAresta("Teresina", "Florianopolis", 2800);
        grafoCapitais.adicionarAresta("Teresina", "Porto Alegre", 3100);
        grafoCapitais.adicionarAresta("Teresina", "Manaus", 2900);
        grafoCapitais.adicionarAresta("Teresina", "Macapa", 1200);
        grafoCapitais.adicionarAresta("Teresina", "Boa Vista", 3900);
        grafoCapitais.adicionarAresta("Teresina", "Belem", 600);
        grafoCapitais.adicionarAresta("Teresina", "Brasilia", 1400);
        grafoCapitais.adicionarAresta("Teresina", "Cuiaba", 2000);
        grafoCapitais.adicionarAresta("Teresina", "Campo Grande", 2100);
        grafoCapitais.adicionarAresta("Teresina", "Goiania", 1600);
        grafoCapitais.adicionarAresta("Teresina", "Natal", 900);
        grafoCapitais.adicionarAresta("Teresina", "Joao Pessoa", 1000);
        grafoCapitais.adicionarAresta("Teresina", "Aracaju", 1200);
        grafoCapitais.adicionarAresta("Teresina", "Maceio", 1300);
        grafoCapitais.adicionarAresta("Teresina", "Salvador", 1400);
        grafoCapitais.adicionarAresta("Teresina", "Fortaleza", 800);
        grafoCapitais.adicionarAresta("Teresina", "Recife", 1100);
        grafoCapitais.adicionarAresta("Teresina", "Palmas", 900);
        grafoCapitais.adicionarAresta("Teresina", "Porto Velho", 2900);
        grafoCapitais.adicionarAresta("Teresina", "Rio Branco", 3000);

        // Conexões a partir de Natal
        grafoCapitais.adicionarAresta("Natal", "Sao Luis", 1100);
        grafoCapitais.adicionarAresta("Natal", "Belo Horizonte", 2100);
        grafoCapitais.adicionarAresta("Natal", "Vitoria", 2300);
        grafoCapitais.adicionarAresta("Natal", "Rio de Janeiro", 2400);
        grafoCapitais.adicionarAresta("Natal", "Sao Paulo", 2600);
        grafoCapitais.adicionarAresta("Natal", "Curitiba", 2900);
        grafoCapitais.adicionarAresta("Natal", "Florianopolis", 3100);
        grafoCapitais.adicionarAresta("Natal", "Porto Alegre", 3400);
        grafoCapitais.adicionarAresta("Natal", "Manaus", 4200);
        grafoCapitais.adicionarAresta("Natal", "Macapa", 2000);
        grafoCapitais.adicionarAresta("Natal", "Boa Vista", 5200);
        grafoCapitais.adicionarAresta("Natal", "Belem", 1600);
        grafoCapitais.adicionarAresta("Natal", "Brasilia", 2000);
        grafoCapitais.adicionarAresta("Natal", "Cuiaba", 2600);
        grafoCapitais.adicionarAresta("Natal", "Campo Grande", 2700);
        grafoCapitais.adicionarAresta("Natal", "Goiania", 2200);
        grafoCapitais.adicionarAresta("Natal", "Teresina", 900);
        grafoCapitais.adicionarAresta("Natal", "Joao Pessoa", 180);
        grafoCapitais.adicionarAresta("Natal", "Aracaju", 550);
        grafoCapitais.adicionarAresta("Natal", "Maceio", 650);
        grafoCapitais.adicionarAresta("Natal", "Salvador", 1000);
        grafoCapitais.adicionarAresta("Natal", "Fortaleza", 530);
        grafoCapitais.adicionarAresta("Natal", "Recife", 280);
        grafoCapitais.adicionarAresta("Natal", "Palmas", 1700);
        grafoCapitais.adicionarAresta("Natal", "Porto Velho", 4000);
        grafoCapitais.adicionarAresta("Natal", "Rio Branco", 4100);

        // Conexões a partir de São Luís
        grafoCapitais.adicionarAresta("Sao Luis", "Sao Paulo", 2700);
        grafoCapitais.adicionarAresta("Sao Luis", "Curitiba", 3000);
        grafoCapitais.adicionarAresta("Sao Luis", "Florianopolis", 3200);
        grafoCapitais.adicionarAresta("Sao Luis", "Porto Alegre", 3500);
        grafoCapitais.adicionarAresta("Sao Luis", "Manaus", 2800);
        grafoCapitais.adicionarAresta("Sao Luis", "Macapa", 1100);
        grafoCapitais.adicionarAresta("Sao Luis", "Boa Vista", 3800);
        grafoCapitais.adicionarAresta("Sao Luis", "Belem", 800);
        grafoCapitais.adicionarAresta("Sao Luis", "Brasilia", 1800);
        grafoCapitais.adicionarAresta("Sao Luis", "Cuiaba", 2400);
        grafoCapitais.adicionarAresta("Sao Luis", "Campo Grande", 2500);
        grafoCapitais.adicionarAresta("Sao Luis", "Goiania", 2000);
        grafoCapitais.adicionarAresta("Sao Luis", "Teresina", 450);
        grafoCapitais.adicionarAresta("Sao Luis", "Natal", 1100);
        grafoCapitais.adicionarAresta("Sao Luis", "Joao Pessoa", 1200);
        grafoCapitais.adicionarAresta("Sao Luis", "Aracaju", 1400);
        grafoCapitais.adicionarAresta("Sao Luis", "Maceio", 1500);
        grafoCapitais.adicionarAresta("Sao Luis", "Salvador", 1600);
        grafoCapitais.adicionarAresta("Sao Luis", "Fortaleza", 1000);
        grafoCapitais.adicionarAresta("Sao Luis", "Recife", 1300);
        grafoCapitais.adicionarAresta("Sao Luis", "Palmas", 1300);
        grafoCapitais.adicionarAresta("Sao Luis", "Porto Velho", 2800);
        grafoCapitais.adicionarAresta("Sao Luis", "Rio Branco", 2900);
        grafoCapitais.adicionarAresta("Sao Luis", "Vitoria", 2200);
        grafoCapitais.adicionarAresta("Sao Luis", "Belo Horizonte", 2000);
        grafoCapitais.adicionarAresta("Sao Luis", "Rio de Janeiro", 2100);

        // Conexões a partir de João Pessoa
        grafoCapitais.adicionarAresta("Joao Pessoa", "Sao Paulo", 2700);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Curitiba", 3000);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Florianopolis", 3200);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Porto Alegre", 3500);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Manaus", 4300);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Macapa", 2100);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Boa Vista", 5300);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Belem", 1700);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Brasilia", 2100);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Cuiaba", 2700);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Campo Grande", 2800);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Goiania", 2300);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Teresina", 1000);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Natal", 180);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Sao Luis", 1200);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Aracaju", 550);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Maceio", 650);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Salvador", 1000);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Fortaleza", 700);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Recife", 120);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Palmas", 1800);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Porto Velho", 4100);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Rio Branco", 4200);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Vitoria", 2300);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Belo Horizonte", 2100);
        grafoCapitais.adicionarAresta("Joao Pessoa", "Rio de Janeiro", 2200);

        // Conexões a partir de Fortaleza
        grafoCapitais.adicionarAresta("Fortaleza", "Sao Paulo", 2900);
        grafoCapitais.adicionarAresta("Fortaleza", "Curitiba", 3200);
        grafoCapitais.adicionarAresta("Fortaleza", "Florianopolis", 3400);
        grafoCapitais.adicionarAresta("Fortaleza", "Porto Alegre", 3700);
        grafoCapitais.adicionarAresta("Fortaleza", "Manaus", 4500);
        grafoCapitais.adicionarAresta("Fortaleza", "Macapa", 2300);
        grafoCapitais.adicionarAresta("Fortaleza", "Boa Vista", 5500);
        grafoCapitais.adicionarAresta("Fortaleza", "Belem", 1900);
        grafoCapitais.adicionarAresta("Fortaleza", "Brasilia", 2200);
        grafoCapitais.adicionarAresta("Fortaleza", "Cuiaba", 2800);
        grafoCapitais.adicionarAresta("Fortaleza", "Campo Grande", 2900);
        grafoCapitais.adicionarAresta("Fortaleza", "Goiania", 2400);
        grafoCapitais.adicionarAresta("Fortaleza", "Teresina", 800);
        grafoCapitais.adicionarAresta("Fortaleza", "Natal", 530);
        grafoCapitais.adicionarAresta("Fortaleza", "Sao Luis", 1000);
        grafoCapitais.adicionarAresta("Fortaleza", "Joao Pessoa", 700);
        grafoCapitais.adicionarAresta("Fortaleza", "Aracaju", 1100);
        grafoCapitais.adicionarAresta("Fortaleza", "Maceio", 1200);
        grafoCapitais.adicionarAresta("Fortaleza", "Salvador", 1400);
        grafoCapitais.adicionarAresta("Fortaleza", "Recife", 800);
        grafoCapitais.adicionarAresta("Fortaleza", "Palmas", 1900);
        grafoCapitais.adicionarAresta("Fortaleza", "Porto Velho", 4300);
        grafoCapitais.adicionarAresta("Fortaleza", "Rio Branco", 4400);
        grafoCapitais.adicionarAresta("Fortaleza", "Vitoria", 2400);
        grafoCapitais.adicionarAresta("Fortaleza", "Belo Horizonte", 2200);
        grafoCapitais.adicionarAresta("Fortaleza", "Rio de Janeiro", 2300);

        // Conexões a partir de Recife
        grafoCapitais.adicionarAresta("Recife", "Sao Paulo", 2700);
        grafoCapitais.adicionarAresta("Recife", "Curitiba", 3000);
        grafoCapitais.adicionarAresta("Recife", "Florianopolis", 3200);
        grafoCapitais.adicionarAresta("Recife", "Porto Alegre", 3500);
        grafoCapitais.adicionarAresta("Recife", "Manaus", 4400);
        grafoCapitais.adicionarAresta("Recife", "Macapa", 2200);
        grafoCapitais.adicionarAresta("Recife", "Boa Vista", 5400);
        grafoCapitais.adicionarAresta("Recife", "Belem", 1800);
        grafoCapitais.adicionarAresta("Recife", "Brasilia", 2100);
        grafoCapitais.adicionarAresta("Recife", "Cuiaba", 2700);
        grafoCapitais.adicionarAresta("Recife", "Campo Grande", 2800);
        grafoCapitais.adicionarAresta("Recife", "Goiania", 2300);
        grafoCapitais.adicionarAresta("Recife", "Teresina", 1100);
        grafoCapitais.adicionarAresta("Recife", "Natal", 280);
        grafoCapitais.adicionarAresta("Recife", "Sao Luis", 1300);
        grafoCapitais.adicionarAresta("Recife", "Joao Pessoa", 120);
        grafoCapitais.adicionarAresta("Recife", "Aracaju", 550);
        grafoCapitais.adicionarAresta("Recife", "Maceio", 650);
        grafoCapitais.adicionarAresta("Recife", "Salvador", 1000);
        grafoCapitais.adicionarAresta("Recife", "Fortaleza", 800);
        grafoCapitais.adicionarAresta("Recife", "Palmas", 1800);
        grafoCapitais.adicionarAresta("Recife", "Porto Velho", 4200);
        grafoCapitais.adicionarAresta("Recife", "Rio Branco", 4300);
        grafoCapitais.adicionarAresta("Recife", "Vitoria", 2300);
        grafoCapitais.adicionarAresta("Recife", "Belo Horizonte", 2100);
        grafoCapitais.adicionarAresta("Recife", "Rio de Janeiro", 2200);

        // Conexões a partir de Maceió
        grafoCapitais.adicionarAresta("Maceio", "Sao Paulo", 2500);
        grafoCapitais.adicionarAresta("Maceio", "Curitiba", 2800);
        grafoCapitais.adicionarAresta("Maceio", "Florianopolis", 3000);
        grafoCapitais.adicionarAresta("Maceio", "Porto Alegre", 3300);
        grafoCapitais.adicionarAresta("Maceio", "Manaus", 4200);
        grafoCapitais.adicionarAresta("Maceio", "Macapa", 2000);
        grafoCapitais.adicionarAresta("Maceio", "Boa Vista", 5200);
        grafoCapitais.adicionarAresta("Maceio", "Belem", 1600);
        grafoCapitais.adicionarAresta("Maceio", "Brasilia", 1900);
        grafoCapitais.adicionarAresta("Maceio", "Cuiaba", 2500);
        grafoCapitais.adicionarAresta("Maceio", "Campo Grande", 2600);
        grafoCapitais.adicionarAresta("Maceio", "Goiania", 2100);
        grafoCapitais.adicionarAresta("Maceio", "Teresina", 1300);
        grafoCapitais.adicionarAresta("Maceio", "Natal", 650);
        grafoCapitais.adicionarAresta("Maceio", "Sao Luis", 1500);
        grafoCapitais.adicionarAresta("Maceio", "Joao Pessoa", 650);
        grafoCapitais.adicionarAresta("Maceio", "Aracaju", 300);
        grafoCapitais.adicionarAresta("Maceio", "Salvador", 600);
        grafoCapitais.adicionarAresta("Maceio", "Fortaleza", 1200);
        grafoCapitais.adicionarAresta("Maceio", "Recife", 650);
        grafoCapitais.adicionarAresta("Maceio", "Palmas", 1600);
        grafoCapitais.adicionarAresta("Maceio", "Porto Velho", 4000);
        grafoCapitais.adicionarAresta("Maceio", "Rio Branco", 4100);
        grafoCapitais.adicionarAresta("Maceio", "Vitoria", 2100);
        grafoCapitais.adicionarAresta("Maceio", "Belo Horizonte", 1900);
        grafoCapitais.adicionarAresta("Maceio", "Rio de Janeiro", 2000);

        // Conexões a partir de Aracaju
        grafoCapitais.adicionarAresta("Aracaju", "Sao Paulo", 2300);
        grafoCapitais.adicionarAresta("Aracaju", "Curitiba", 2600);
        grafoCapitais.adicionarAresta("Aracaju", "Florianopolis", 2800);
        grafoCapitais.adicionarAresta("Aracaju", "Porto Alegre", 3100);
        grafoCapitais.adicionarAresta("Aracaju", "Manaus", 4000);
        grafoCapitais.adicionarAresta("Aracaju", "Macapa", 1800);
        grafoCapitais.adicionarAresta("Aracaju", "Boa Vista", 5000);
        grafoCapitais.adicionarAresta("Aracaju", "Belem", 1400);
        grafoCapitais.adicionarAresta("Aracaju", "Brasilia", 1700);
        grafoCapitais.adicionarAresta("Aracaju", "Cuiaba", 2300);
        grafoCapitais.adicionarAresta("Aracaju", "Campo Grande", 2400);
        grafoCapitais.adicionarAresta("Aracaju", "Goiania", 1900);
        grafoCapitais.adicionarAresta("Aracaju", "Teresina", 1200);
        grafoCapitais.adicionarAresta("Aracaju", "Natal", 550);
        grafoCapitais.adicionarAresta("Aracaju", "Sao Luis", 1400);
        grafoCapitais.adicionarAresta("Aracaju", "Joao Pessoa", 550);
        grafoCapitais.adicionarAresta("Aracaju", "Maceio", 300);
        grafoCapitais.adicionarAresta("Aracaju", "Salvador", 350);
        grafoCapitais.adicionarAresta("Aracaju", "Fortaleza", 1100);
        grafoCapitais.adicionarAresta("Aracaju", "Recife", 550);
        grafoCapitais.adicionarAresta("Aracaju", "Palmas", 1400);
        grafoCapitais.adicionarAresta("Aracaju", "Porto Velho", 3800);
        grafoCapitais.adicionarAresta("Aracaju", "Rio Branco", 3900);
        grafoCapitais.adicionarAresta("Aracaju", "Vitoria", 1900);
        grafoCapitais.adicionarAresta("Aracaju", "Belo Horizonte", 1700);
        grafoCapitais.adicionarAresta("Aracaju", "Rio de Janeiro", 1800);

        // Conexões a partir de Salvador
        grafoCapitais.adicionarAresta("Salvador", "Sao Paulo", 1900);
        grafoCapitais.adicionarAresta("Salvador", "Curitiba", 2200);
        grafoCapitais.adicionarAresta("Salvador", "Florianopolis", 2400);
        grafoCapitais.adicionarAresta("Salvador", "Porto Alegre", 2700);
        grafoCapitais.adicionarAresta("Salvador", "Manaus", 3800);
        grafoCapitais.adicionarAresta("Salvador", "Macapa", 1600);
        grafoCapitais.adicionarAresta("Salvador", "Boa Vista", 4800);
        grafoCapitais.adicionarAresta("Salvador", "Belem", 1200);
        grafoCapitais.adicionarAresta("Salvador", "Brasilia", 1400);
        grafoCapitais.adicionarAresta("Salvador", "Cuiaba", 2000);
        grafoCapitais.adicionarAresta("Salvador", "Campo Grande", 2100);
        grafoCapitais.adicionarAresta("Salvador", "Goiania", 1600);
        grafoCapitais.adicionarAresta("Salvador", "Teresina", 1400);
        grafoCapitais.adicionarAresta("Salvador", "Natal", 1000);
        grafoCapitais.adicionarAresta("Salvador", "Sao Luis", 1600);
        grafoCapitais.adicionarAresta("Salvador", "Joao Pessoa", 1000);
        grafoCapitais.adicionarAresta("Salvador", "Aracaju", 350);
        grafoCapitais.adicionarAresta("Salvador", "Maceio", 600);
        grafoCapitais.adicionarAresta("Salvador", "Fortaleza", 1400);
        grafoCapitais.adicionarAresta("Salvador", "Recife", 1000);
        grafoCapitais.adicionarAresta("Salvador", "Palmas", 1200);
        grafoCapitais.adicionarAresta("Salvador", "Porto Velho", 3600);
        grafoCapitais.adicionarAresta("Salvador", "Rio Branco", 3700);
        grafoCapitais.adicionarAresta("Salvador", "Vitoria", 1500);
        grafoCapitais.adicionarAresta("Salvador", "Belo Horizonte", 1300);
        grafoCapitais.adicionarAresta("Salvador", "Rio de Janeiro", 1600);      
        //centro-oeste
        grafoCapitais.adicionarAresta("Brasilia", "Sao Paulo", 11500);
        grafoCapitais.adicionarAresta("Brasilia", "Curitiba", 12000);
        grafoCapitais.adicionarAresta("Brasilia", "Florianopolis", 12500);
        grafoCapitais.adicionarAresta("Brasilia", "Porto Alegre", 13000);
        grafoCapitais.adicionarAresta("Brasilia", "Manaus", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Macapa", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Boa Vista", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Belem", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Rio Branco", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Cuiaba", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Campo Grande", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Goiania", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Teresina", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Natal", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Sao Luis", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Joao Pessoa", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Aracaju", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Maceio", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Salvador", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Fortaleza", 3000);   
        grafoCapitais.adicionarAresta("Brasilia", "Recife", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Palmas", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Porto Velho", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Vitoria", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Belo Horizonte", 3000);
        grafoCapitais.adicionarAresta("Brasilia", "Rio de Janeiro", 3000);
        grafoCapitais.adicionarAresta("Goiania", "Sao Paulo", 850);
        grafoCapitais.adicionarAresta("Goiania", "Curitiba", 1100);
        grafoCapitais.adicionarAresta("Goiania", "Florianopolis", 1300);
        grafoCapitais.adicionarAresta("Goiania", "Porto Alegre", 1600);
        grafoCapitais.adicionarAresta("Goiania", "Manaus", 3400);
        grafoCapitais.adicionarAresta("Goiania", "Macapa", 2600);
        grafoCapitais.adicionarAresta("Goiania", "Boa Vista", 4300);
        grafoCapitais.adicionarAresta("Goiania", "Belem", 2100);
        grafoCapitais.adicionarAresta("Goiania", "Rio Branco", 2900);
        grafoCapitais.adicionarAresta("Goiania", "Brasilia", 200);
        grafoCapitais.adicionarAresta("Goiania", "Cuiaba", 930);
        grafoCapitais.adicionarAresta("Goiania", "Campo Grande", 900);
        grafoCapitais.adicionarAresta("Goiania", "Teresina", 1600);
        grafoCapitais.adicionarAresta("Goiania", "Natal", 2300);
        grafoCapitais.adicionarAresta("Goiania", "Sao Luis", 1900);
        grafoCapitais.adicionarAresta("Goiania", "Joao Pessoa", 2200);
        grafoCapitais.adicionarAresta("Goiania", "Aracaju", 1600);
        grafoCapitais.adicionarAresta("Goiania", "Maceio", 1800);
        grafoCapitais.adicionarAresta("Goiania", "Salvador", 1500);
        grafoCapitais.adicionarAresta("Goiania", "Fortaleza", 2200);
        grafoCapitais.adicionarAresta("Goiania", "Recife", 2100);
        grafoCapitais.adicionarAresta("Goiania", "Palmas", 800);
        grafoCapitais.adicionarAresta("Goiania", "Porto Velho", 2200);
        grafoCapitais.adicionarAresta("Goiania", "Vitoria", 1200);
        grafoCapitais.adicionarAresta("Goiania", "Belo Horizonte", 800);
        grafoCapitais.adicionarAresta("Goiania", "Rio de Janeiro", 1100);

        grafoCapitais.adicionarAresta("Cuiaba", "Sao Paulo", 1450);
        grafoCapitais.adicionarAresta("Cuiaba", "Curitiba", 1650);
        grafoCapitais.adicionarAresta("Cuiaba", "Florianopolis", 1850);
        grafoCapitais.adicionarAresta("Cuiaba", "Porto Alegre", 2150);
        grafoCapitais.adicionarAresta("Cuiaba", "Manaus", 2800);
        grafoCapitais.adicionarAresta("Cuiaba", "Macapa", 2800);
        grafoCapitais.adicionarAresta("Cuiaba", "Boa Vista", 3900);
        grafoCapitais.adicionarAresta("Cuiaba", "Belem", 2400);
        grafoCapitais.adicionarAresta("Cuiaba", "Rio Branco", 2200);
        grafoCapitais.adicionarAresta("Cuiaba", "Brasilia", 1130);
        grafoCapitais.adicionarAresta("Cuiaba", "Goiania", 930);
        grafoCapitais.adicionarAresta("Cuiaba", "Campo Grande", 700);
        grafoCapitais.adicionarAresta("Cuiaba", "Teresina", 2000);
        grafoCapitais.adicionarAresta("Cuiaba", "Natal", 2800);
        grafoCapitais.adicionarAresta("Cuiaba", "Sao Luis", 2300);
        grafoCapitais.adicionarAresta("Cuiaba", "Joao Pessoa", 2700);
        grafoCapitais.adicionarAresta("Cuiaba", "Aracaju", 2200);
        grafoCapitais.adicionarAresta("Cuiaba", "Maceio", 2400);
        grafoCapitais.adicionarAresta("Cuiaba", "Salvador", 2100);
        grafoCapitais.adicionarAresta("Cuiaba", "Fortaleza", 2600);
        grafoCapitais.adicionarAresta("Cuiaba", "Recife", 2500);
        grafoCapitais.adicionarAresta("Cuiaba", "Palmas", 1400);
        grafoCapitais.adicionarAresta("Cuiaba", "Porto Velho", 1450);
        grafoCapitais.adicionarAresta("Cuiaba", "Vitoria", 1900);
        grafoCapitais.adicionarAresta("Cuiaba", "Belo Horizonte", 1650);
        grafoCapitais.adicionarAresta("Cuiaba", "Rio de Janeiro", 1750);

        grafoCapitais.adicionarAresta("Campo Grande", "Sao Paulo", 990);
        grafoCapitais.adicionarAresta("Campo Grande", "Curitiba", 1200);
        grafoCapitais.adicionarAresta("Campo Grande", "Florianopolis", 1350);
        grafoCapitais.adicionarAresta("Campo Grande", "Porto Alegre", 1650);
        grafoCapitais.adicionarAresta("Campo Grande", "Manaus", 2930);
        grafoCapitais.adicionarAresta("Campo Grande", "Macapa", 3100);
        grafoCapitais.adicionarAresta("Campo Grande", "Boa Vista", 4000);
        grafoCapitais.adicionarAresta("Campo Grande", "Belem", 2800);
        grafoCapitais.adicionarAresta("Campo Grande", "Rio Branco", 2900);
        grafoCapitais.adicionarAresta("Campo Grande", "Brasilia", 1130);
        grafoCapitais.adicionarAresta("Campo Grande", "Goiania", 900);
        grafoCapitais.adicionarAresta("Campo Grande", "Cuiaba", 700);
        grafoCapitais.adicionarAresta("Campo Grande", "Teresina", 2300);
        grafoCapitais.adicionarAresta("Campo Grande", "Natal", 3100);
        grafoCapitais.adicionarAresta("Campo Grande", "Sao Luis", 2700);
        grafoCapitais.adicionarAresta("Campo Grande", "Joao Pessoa", 3000);
        grafoCapitais.adicionarAresta("Campo Grande", "Aracaju", 2400);
        grafoCapitais.adicionarAresta("Campo Grande", "Maceio", 2600);
        grafoCapitais.adicionarAresta("Campo Grande", "Salvador", 2200);
        grafoCapitais.adicionarAresta("Campo Grande", "Fortaleza", 2900);
        grafoCapitais.adicionarAresta("Campo Grande", "Recife", 2800);
        grafoCapitais.adicionarAresta("Campo Grande", "Palmas", 1700);
        grafoCapitais.adicionarAresta("Campo Grande", "Porto Velho", 1900);
        grafoCapitais.adicionarAresta("Campo Grande", "Vitoria", 1700);
        grafoCapitais.adicionarAresta("Campo Grande", "Belo Horizonte", 1450);
        grafoCapitais.adicionarAresta("Campo Grande", "Rio de Janeiro", 1450);
    }
}